dev:
  host: foia.ssh.prod.acquia-sites.com
  options:
    ac-env: prod
    ac-realm: prod
    ac-site: foia
  paths:
    drush-script: drush9
  root: /var/www/html/foia.prod/docroot
  uri: foia.prod.acquia-sites.com
  user: foia.prod
livedev:
  options:
    parent: '@foia.prod'
  root: /mnt/gfs/foia.prod/livedev/docroot
